# This is a basic workflow to help you get started with Actions

name: service-scorecard

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    - cron: "15 12 * * *"
  workflow_dispatch:
    inputs:
      name:
        description: "retrieve scorecard details from service catalog and post the message to user's Teams or Slack channel"
        required: true
        default: "Mona the Octocat"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run powershell script to get service catalog details
        id: main-script
        shell: powershell
        run: |
          $result = &.\serviceCatalog.ps1
          echo "::set-output name=scorecard::$result"
        env:
          SERVICE_CATALOG_TOKEN: ${{ secrets.SERVICE_CATALOG_TOKEN }}

      - name: Push Notification
        uses: ProtocolRedefined/Dynamic-Template-Engine@master
        with:
          repoName: ProtocolRedefined/Service-Catalog-Scorecard
          branchName: main
          data: '{ "message" : ${{ steps.main-script.outputs.scorecard }} }'
          templateType: HandleBars
          sourceType: CatalogScoreCard
          ClientType: Teams
